apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: alternative-wallaby-python 
  janus-idp.io/tekton: alternative-wallaby-python
  backstage.io/kubernetes-id: alternative-wallaby-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: alternative-wallaby-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  