apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: alternative-wallaby-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: alternative-wallaby-python 
  name: alternative-wallaby-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: alternative-wallaby-python 
