apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: alternative-wallaby-python-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/alternative-wallaby-python-gitops